#ifndef COMMON_NOTICE_H
#define COMMON_NOTICE_H

enum errno_t
{
    ERR_NULLPTR = 100,
    ERR_SOCKFD_INVALID = 1000,
    ERR_FCNTL_FAILED,
    ERR_SOCKET_FAILED,
    ERR_LISTEN_FAILED,
    ERR_BIND_FAILED,
    ERR_SETSOCKOPT_FAILED,
    ERR_CONNECT_FAILED,
    ERR_CMD_NOT_FOUND,
    ERR_CLNT_IS_BROKEN,
    ERR_READPACKET_EMPTY,
    ERR_CLNT_IS_CLOSED,
    ERR_NO_DATA_TO_READ,
};

#endif // COMMON_NOTICE_H
